### ISSUE TITLE
Where to get this "postman/api/id"? 

### ISSUE THREAD

**Issue by VasKumarSel** [postman-solutions-eng/backstage-postman-plugin#6]
Hi,
i have installed both frontend and backend Postman plugins. Added PostmanCard component inside EntityLayout. And i have published a api in postman. Added workspace id and api id (from info button in postman app) inside yaml file. Added apikey and baseurl in app-config as well. Still iam getting "Request failed with status code 400". Is there any issue with postman/api/id. How to get this postman/api/id from postman ?

Thanks in advance

**Comment by aphanor** [comment]
Hi @VasKumarSel  - you should be able to get the API ID from the information section in the API view. Here is an example: 

<img width="1485" alt="api:id" src="https://github.com/user-attachments/assets/dade5762-1605-4956-a91a-9e2dd0a73859">

If you are still experiencing the same issue after using this ID, could you share your Postman team domain, which you can find at https://go.postman.co/settings/team/general? I will have a look for you.

**Comment by VasKumarSel** [comment]
Hi @aphanor Please find the team domain and a sample request which is failing even with correct api id. Kindly check and let me know if you need any.
Team domain: **planetary-star-547941-7213**

This image shows api id from info button.

<img width="887" alt="postman-api_id" src="https://github.com/user-attachments/assets/d5456c7e-5dee-4c64-b6b3-e7170cfdf9ee">

 I am using the same in my yaml file. Still iam getting the 400 bad request.

//API information in yaml file
**apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: claimsdsd-form-v1.0
  postman/workspace/id: 3552e2c2-f147-4da3-8073-7400a69aa191
  postman/api/id: 39807572-0280884e-c568-4887-90f4-f5776072cd2f**
//

**Request details**
http://localhost:7007/api/postman/apis/39807572-0280884e-c568-4887-90f4-f5776072cd2f
Request Method: GET
Status Code: 400 Bad Request

**Response:**
{"error":"Request failed with status code 400","status":400}

**Comment by aphanor-postman** [comment]
Hi @VasKumarSel - I think the term "API" might have caused some confusion. Let me clarify:

**API View in Backstage**
Postman has a feature called APIs, which allows you to create an API and sync the API definition to its collection. This Postman backstage plugin allows you to display your API content (name, API versions and collections) stored in the APIs tab and visualise it directly within Backstage. Here is an example:

My API in Postman:

![API_in_Postman](https://github.com/user-attachments/assets/cc13b6e8-d4c0-4afd-94f1-54840c16cfb6)

My API information in my `yaml` file:

```
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: users-api
  title: Users API
  description: "My Users API."
  postman/domain: "MY_TEAM_DOMAIN"
  postman/api/id: "3fc0bfef-c6e0-45da-ab65-9486fec8a478"
  # others options
```

API View in Backstage:

![API_view_in_backstage](https://github.com/user-attachments/assets/3af08192-d8be-4d64-aeb5-03c8e9cac3f8)

**Collections**
If you have standalone collections stored in the **Collections** tab, you can also retrieve the collection ID and configure it in your project like this:

Collection in Postman:

![collection_in_postman](https://github.com/user-attachments/assets/0091e146-466b-469e-8a24-2f4e1801ad90)

Collection configuration in my `yaml` file:

```
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: nova-security-api
  title: NOVA Security API
  description: "This API to a collection in Postman."
  postman/collections/ids: ["23451556-d2e6df12-de0c-405f-bb68-7376545eb34f"]
```

Collection view in my Backstage catalogue:

![collection_in_backstage](https://github.com/user-attachments/assets/6b0efc77-8cd3-48aa-989a-de0298ab9327)

To finish, I would recommend checking your postman configuration in your `app-config.yaml `file. It should look as follows:
```
postman:
  baseUrl: https://api.postman.com/
  apiKey: POSTMAN_API_KEY
  entityProviderSynchInterval: 2
  cache:
    ttl: 60000
```
